// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveWorkspace() {
  return window['go']['backend']['App']['GetActiveWorkspace']();
}

export function GetContextList() {
  return window['go']['backend']['App']['GetContextList']();
}

export function RunCommand(arg1) {
  return window['go']['backend']['App']['RunCommand'](arg1);
}
