// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveWorkspace() {
  return window['go']['backend']['App']['GetActiveWorkspace']();
}

export function GetContextList() {
  return window['go']['backend']['App']['GetContextList']();
}

export function GetNamespaces() {
  return window['go']['backend']['App']['GetNamespaces']();
}

export function GetPodList(arg1, arg2) {
  return window['go']['backend']['App']['GetPodList'](arg1, arg2);
}

export function GetWorkspaceList() {
  return window['go']['backend']['App']['GetWorkspaceList']();
}

export function RunCommand(arg1) {
  return window['go']['backend']['App']['RunCommand'](arg1);
}

export function StreamLog(arg1, arg2, arg3) {
  return window['go']['backend']['App']['StreamLog'](arg1, arg2, arg3);
}

export function StreamPods(arg1, arg2) {
  return window['go']['backend']['App']['StreamPods'](arg1, arg2);
}
