// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetActiveWorkspace():Promise<backend.GenerictResult[gube/backend/models>;

export function GetContextList():Promise<backend.GenerictResult[[]*k8s>;

export function RunCommand(arg1:string):Promise<backend.GenerictResult[string]>;
