// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetActiveWorkspace():Promise<models.GenerictResult[gube/backend/models>;

export function GetContextList():Promise<models.GenerictResult[[]*k8s>;

export function GetPodList(arg1:string,arg2:string):Promise<models.GenerictResult[[]k8s>;

export function GetWorkspaceList():Promise<models.GenerictResult[[]gube/backend/models>;

export function RunCommand(arg1:string):Promise<models.GenerictResult[string]>;

export function StreamLog(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StreamPods(arg1:string,arg2:string):Promise<void>;
