// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kubernetes} from '../models';
import {models} from '../models';
import {context} from '../models';

export function GetContextClient(arg1:string):Promise<kubernetes.Clientset>;

export function GetContextList():Promise<models.GenerictResult[[]*k8s>;

export function SetContext(arg1:context.Context):Promise<void>;
