// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContextClient(arg1) {
  return window['go']['services']['ContextService']['GetContextClient'](arg1);
}

export function GetContextList() {
  return window['go']['services']['ContextService']['GetContextList']();
}

export function SetContext(arg1) {
  return window['go']['services']['ContextService']['SetContext'](arg1);
}
