// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';
import {services} from '../models';

export function GetNamespaceList():Promise<models.GenerictResult[[]*k8s>;

export function SetContext(arg1:context.Context,arg2:services.ContextService):Promise<void>;
