// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPodList(arg1, arg2, arg3) {
  return window['go']['services']['PodService']['GetPodList'](arg1, arg2, arg3);
}

export function SetContext(arg1, arg2, arg3) {
  return window['go']['services']['PodService']['SetContext'](arg1, arg2, arg3);
}

export function StreamPods(arg1, arg2, arg3) {
  return window['go']['services']['PodService']['StreamPods'](arg1, arg2, arg3);
}
