// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function GetActiveWorkspace():Promise<models.GenerictResult[gube/backend/models>;

export function GetAllWorkspace():Promise<models.GenerictResult[[]gube/backend/models>;

export function SetContext(arg1:context.Context):Promise<void>;
