// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveWorkspace() {
  return window['go']['services']['WorkspaceService']['GetActiveWorkspace']();
}

export function GetAllWorkspace() {
  return window['go']['services']['WorkspaceService']['GetAllWorkspace']();
}

export function SetContext(arg1) {
  return window['go']['services']['WorkspaceService']['SetContext'](arg1);
}
